title: Ryoko Noda # your name (or website title) here
logo: "/images/portrait.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  Specialty: LLMs and microservices 
  <br><br>
  <a href="https://www.linkedin.com/in/ryoko-noda-3976562b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
